/* Edit this file to update texts, projects and photographs. */
window.SITE_CONTENT = {
  email: 'movaru09@gmail.com',
  orcid: 'https://orcid.org/0000-0002-3246-9984',
  cv: 'https://sites.google.com/view/monicavasco/cv',
  portrait: '',
  languages: {
    en: {
      nav: ['About', 'Research', 'Fieldwork', 'Teaching', 'Contact'],
      discipline: 'Experimental & behavioral economics',
      affiliation: 'Postdoctoral researcher · LABEL · University of Southern California',
      headline: 'Learning and decisions<br>in a connected world.',
      bio: 'I study how people learn, coordinate, and make decisions in social networks, with a particular focus on children and adolescents. My research combines lab-in-the-field experiments with social network analysis.',
      bio2: 'Through collaborative projects, I contribute to experimental design, implementation, fieldwork coordination, data analysis, and academic writing. My experimental research spans Spain, Los Angeles, and Madagascar.',
      cv: 'View CV', research: 'Explore my research', portrait: 'Portrait photograph',
      featuredLabel: 'A closer look', featured: 'Selected research',
      featuredIntro: 'Peer relationships and perceptions of social networks are central to my research agenda.',
      researchLabel: 'Research agenda', researchTitle: 'Papers & ongoing projects',
      researchIntro: 'Experimental economics, social learning, strategic interaction, and the structure of social relationships.',
      filters: ['All research', 'Published papers', 'Working papers', 'Work in progress'],
      fieldLabel: 'Beyond the laboratory', fieldTitle: 'Experiments in the field',
      fieldIntro: 'Designing and implementing experiments with schools, research teams, and local partners.',
      photoPending: 'Photograph to be added', photoPrev: 'Previous photograph', photoNext: 'Next photograph',
      photoRegion: 'Fieldwork photo carousel', photoGo: 'Show photograph', photoOf: 'of',
      teachingLabel: 'Teaching', teachingTitle: 'Research-informed teaching',
      teachingIntro: 'University teaching experience in English and Spanish, as instructor of record and teaching assistant.',
      instructor: 'Instructor of record', assistant: 'Teaching assistant',
      english: 'English', spanish: 'Spanish',
      academicLabel: 'Academic background', backgroundTitle: 'From Córdoba to Los Angeles',
      background: 'I earned my PhD in Data Science at Universidad Loyola Andalucía in July 2024, supported by an FPU doctoral fellowship. My training also includes an MSc in Economics at the University of the Basque Country, a research methods master’s degree, and degrees in Business Administration and Law. During my doctorate, I completed a research visit at the University of Essex.',
      service: 'Academic activities & applied research',
      serviceText: 'Co-organizer of the Borchard Colloquium, Missillac, France (2026). Research collaboration with Fundación Cotec on teachers’ decision-making and biases.',
      contactLabel: 'Get in touch', contactTitle: 'Let’s connect.',
      contactText: 'I welcome conversations about research collaborations and research and teaching opportunities in Spain.',
      footer: 'Experimental economics · Social networks · Field experiments',
      paperLink: 'Read paper', paperNote: 'Project in progress', groupHeadings: ['Published papers', 'Working papers', 'Work in progress'],
      results: 'research items',
    },
    es: {
      nav: ['Perfil', 'Investigación', 'Trabajo de campo', 'Docencia', 'Contacto'],
      discipline: 'Economía experimental y del comportamiento',
      affiliation: 'Investigadora postdoctoral · LABEL · University of Southern California',
      headline: 'Aprendizaje y decisiones<br>en un mundo conectado.',
      bio: 'Estudio cómo las personas aprenden, se coordinan y toman decisiones en redes sociales, con especial atención a niños y adolescentes. Mi investigación combina experimentos de laboratorio en campo con análisis de redes sociales.',
      bio2: 'En proyectos colaborativos, participo en el diseño e implementación experimental, la coordinación del trabajo de campo, el análisis de datos y la escritura académica. Mi experiencia experimental abarca España, Los Ángeles y Madagascar.',
      cv: 'Ver CV', research: 'Explorar mi investigación', portrait: 'Fotografía de retrato',
      featuredLabel: 'En detalle', featured: 'Investigación destacada',
      featuredIntro: 'Las relaciones entre iguales y la percepción de las redes sociales son centrales en mi agenda de investigación.',
      researchLabel: 'Agenda de investigación', researchTitle: 'Artículos y proyectos',
      researchIntro: 'Economía experimental, aprendizaje social, interacción estratégica y estructura de las relaciones sociales.',
      filters: ['Todos', 'Publicaciones', 'Working papers', 'Trabajos en curso'],
      fieldLabel: 'Más allá del laboratorio', fieldTitle: 'Experimentos en campo',
      fieldIntro: 'Diseño e implementación de experimentos con colegios, equipos de investigación y colaboradores locales.',
      photoPending: 'Fotografía pendiente', photoPrev: 'Fotografía anterior', photoNext: 'Fotografía siguiente',
      photoRegion: 'Carrusel de fotografías del trabajo de campo', photoGo: 'Mostrar fotografía', photoOf: 'de',
      teachingLabel: 'Docencia', teachingTitle: 'Docencia vinculada a la investigación',
      teachingIntro: 'Experiencia docente universitaria en inglés y español, como responsable de asignatura y ayudante de docencia.',
      instructor: 'Responsable de asignatura', assistant: 'Ayudante de docencia',
      english: 'Inglés', spanish: 'Español',
      academicLabel: 'Trayectoria académica', backgroundTitle: 'De Córdoba a Los Ángeles',
      background: 'Me doctoré en Data Science en la Universidad Loyola Andalucía en julio de 2024, con una beca FPU. Mi formación incluye un máster en Economía en la Universidad del País Vasco, un máster en métodos de investigación y los grados en ADE y Derecho. Durante el doctorado realicé una estancia de investigación en la University of Essex.',
      service: 'Actividad académica e investigación aplicada',
      serviceText: 'Coorganizadora del Borchard Colloquium, Missillac, Francia (2026). Colaboración investigadora con Fundación Cotec sobre toma de decisiones y sesgos del profesorado.',
      contactLabel: 'Contacto', contactTitle: 'Hablemos.',
      contactText: 'Estoy interesada en colaboraciones de investigación y oportunidades de investigación y docencia en España.',
      footer: 'Economía experimental · Redes sociales · Experimentos de campo',
      paperLink: 'Leer artículo', paperNote: 'Proyecto en curso', groupHeadings: ['Publicaciones', 'Working papers', 'Trabajos en curso'],
      results: 'trabajos de investigación',
    }
  },
  featured: [
    {id: 'bullying', title: 'The Social Footprint of Bullying: Evidence from Signed Peer Nominations and Tie Strength',
      en: 'Understanding bullying through peer nominations, the sign of social relationships, and the strength of interpersonal ties.',
      es: 'Comprender el acoso escolar a través de las nominaciones entre iguales, el signo de las relaciones y la intensidad de los vínculos.'},
    {id: 'perception', title: 'Perception of social network relationships among adolescents',
      en: 'Studying how adolescents perceive the social relationships around them.',
      es: 'Estudiar cómo los adolescentes perciben las relaciones sociales de su entorno.'}
  ],
  papers: [
    {category: 'published', year: '2025', title: 'Economic preferences and cognitive abilities among teenagers in Spain', authors: 'M. Vasco et al.', venue: 'Scientific Data, 12, 7', url: 'https://doi.org/10.1038/s41597-024-04298-6'},
    {category: 'published', year: '2025', title: 'Holt-Laury as a gumball machine', authors: 'M. Vasco & M. J. Vázquez-De Francisco', venue: 'PLOS ONE, 20(4), e0320576', url: 'https://doi.org/10.1371/journal.pone.0320576'},
    {category: 'published', year: '2023', title: 'The adventure of running experiments with teenagers', authors: 'A. Alfonso, P. Brañas-Garza, D. Jorrat, P. Lomas, B. Prissé, M. Vasco & M. J. Vázquez-De Francisco', venue: 'Journal of Behavioral and Experimental Economics, 102048', url: 'https://doi.org/10.1016/j.socec.2023.102048'},
    {id: 'bullying', category: 'working', title: 'The Social Footprint of Bullying: Evidence from Signed Peer Nominations and Tie Strength', authors: 'P. Brañas-Garza, A. Cabrales, J. Kovářík & M. Vasco', url: ''},
    {category: 'working', title: 'Learning and information transfer: Evidence from an intuitive physics task', authors: 'I. Brocas, J. D. Carrillo, M. Derex & M. Vasco', url: ''},
    {id: 'perception', category: 'progress', title: 'Perception of social network relationships among adolescents', authors: 'P. Brañas-Garza, J. Kovářík, F. Mengel & M. Vasco'},
    {category: 'progress', title: 'Gender Differences in Friendship Networks (Across the Globe)', authors: 'J. Kovářík, C.-S. Hsieh & M. Vasco'},
    {category: 'progress', title: 'Networked decision-making and social learning in children and adolescents', authors: 'I. Brocas, J. D. Carrillo & M. Vasco'},
    {category: 'progress', title: 'The microfoundations of herding behavior: Learning, signals, and connectivity in children’s networks', authors: 'I. Brocas, J. D. Carrillo, U. Rios & M. Vasco'},
    {category: 'progress', title: 'Development of protective behavior and contagion reasoning in a dynamic network SIS game', authors: 'I. Brocas, J. D. Carrillo & M. Vasco'},
    {category: 'progress', title: 'Friendship, enmity, and in-between: Dimensions of social relationships across development', authors: 'I. Brocas, J. D. Carrillo & M. Vasco'},
    {category: 'progress', title: 'Measuring theory of mind in children and adolescents', authors: 'I. Brocas, J. D. Carrillo & M. Vasco'},
    {category: 'progress', title: 'Leadership Legitimacy, Inequality, and Protests: A Network Experiment with University Students in Madagascar', authors: {en: 'With I. Brocas, J. D. Carrillo, Rajaomason and other collaborators', es: 'Con I. Brocas, J. D. Carrillo, Rajaomason y otros colaboradores'}}
  ],
  photos: [
    {image: '', location: {en: 'Spain', es: 'España'}, topic: {en: 'Learning & coordination', es: 'Aprendizaje y coordinación'},
      caption: {en: 'School-based experiments on social learning and real-time decisions in networks. Experimental design, school liaison, and fieldwork coordination in projects developed at USC.', es: 'Experimentos en colegios sobre aprendizaje social y decisiones en redes en tiempo real. Diseño experimental, contacto con los centros y coordinación del trabajo de campo en proyectos desarrollados en USC.'},
      alt: {en: 'Experimental fieldwork in schools in Spain', es: 'Trabajo experimental en colegios en España'}},
    {image: '', location: {en: 'Los Angeles', es: 'Los Ángeles'}, topic: {en: 'Developmental experiments', es: 'Experimentos sobre el desarrollo'},
      caption: {en: 'Collaborative research at LABEL–USC on learning, coordination, and contagion. Literature review, experimental design, implementation, analysis, and writing across projects.', es: 'Investigación colaborativa en LABEL–USC sobre aprendizaje, coordinación y contagio. Revisión de literatura, diseño, implementación, análisis y escritura en distintos proyectos.'},
      alt: {en: 'Experimental research in Los Angeles', es: 'Investigación experimental en Los Ángeles'}},
    {image: '', location: {en: 'Madagascar', es: 'Madagascar'}, topic: {en: 'Protests & collective action', es: 'Protestas y acción colectiva'},
      caption: {en: 'A network experiment with university students on leadership legitimacy, inequality, and protest participation. Contributions to design, oTree programming, and on-site data collection.', es: 'Un experimento en redes con universitarios sobre legitimidad del liderazgo, desigualdad y participación en protestas. Participación en el diseño, programación en oTree y recogida de datos sobre el terreno.'},
      alt: {en: 'Experimental fieldwork with university students in Madagascar', es: 'Trabajo experimental con universitarios en Madagascar'}}
  ],
  teaching: [
    {title: {en: 'Econometrics', es: 'Econometría'}, years: '2023–2024', role: 'instructor', language: 'english'},
    {title: {en: 'Growth and Development Economics', es: 'Economía del crecimiento y del desarrollo'}, years: '2022–2023', role: 'instructor', language: 'spanish'},
    {title: {en: 'Microeconomics III', es: 'Microeconomía III'}, years: '2022–2024', role: 'assistant', language: 'spanish'}
  ]
};
